kind: Pod
apiVersion: v1
metadata:
  name: nfs-provisioner
spec:
  containers:
    - name: volume-nfs4
      image: wongma7/volume-nfs4
      ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
      securityContext:
        privileged: true
      volumeMounts:
        - name: tmp
          mountPath: /exports
          readOnly: false
  volumes:
    - name: tmp
      hostPath:
        path: /tmp
